backend:
  name: git-gateway
  branch: main

# Configuration locale pour le développement
local_backend: true

# Configuration des médias
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Configuration des messages de commit
commit_messages:
  create: "Content: Add {{collection}} '{{slug}}'"
  update: "Content: Update {{collection}} '{{slug}}'"
  delete: "Content: Delete {{collection}} '{{slug}}'"
  uploadMedia: "Assets: Upload '{{path}}'"
  deleteMedia: "Assets: Delete '{{path}}'"

# Langue de l'interface
locale: 'fr'

collections:
  - name: "home"
    label: "🏠 Accueil"
    files:
      - label: "Page d'accueil"
        name: "main"
        file: "content/home/main.md"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Sous-titre", name: "subtitle", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Carousel"
            name: "carousel"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Titre", name: "title", widget: "string"}

  - name: "services"
    label: "💎 Services"
    files:
      - label: "Liste des Services"
        name: "list"
        file: "content/services/services.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icône", name: "icon", widget: "select", options: ["Crown", "Star", "Gem", "Globe"]}
              - label: "Caractéristiques"
                name: "features"
                widget: "list"
                required: false
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}

  - name: "wellness"
    label: "🧘‍♀️ Bien-être"
    folder: "content/wellness"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Prix", name: "price", widget: "string", required: false}
      - {label: "Durée", name: "duration", widget: "string", required: false}
      - label: "Avantages"
        name: "benefits"
        widget: "list"
        required: false
        field: {label: "Avantage", name: "benefit", widget: "string"}

  - name: "mystical"
    label: "✨ Expériences Mystiques"
    folder: "content/mystical"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Icône", name: "icon", widget: "select", options: ["Sparkle", "Moon", "Compass", "Stars"]}
      - label: "Détails"
        name: "details"
        widget: "list"
        required: false
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "events"
    label: "🎉 Événements"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Icône", name: "icon", widget: "select", options: ["Calendar", "Users", "Gift", "Music"]}
      - label: "Services Inclus"
        name: "services"
        widget: "list"
        field: {label: "Service", name: "service", widget: "string"}
      - label: "Galerie"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Légende", name: "caption", widget: "string"}

  - name: "settings"
    label: "⚙️ Paramètres"
    files:
      - label: "Métadonnées"
        name: "metadata"
        file: "content/settings/metadata.md"
        fields:
          - {label: "Titre du Site", name: "siteTitle", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Mots-clés", name: "keywords", widget: "list"}
          - {label: "Image par défaut", name: "defaultImage", widget: "image"}
      
      - label: "Contact"
        name: "contact"
        file: "content/settings/contact.md"
        fields:
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Téléphone", name: "phone", widget: "string"}
          - {label: "Adresse", name: "address", widget: "string"}
          - {label: "Disponibilité", name: "availability", widget: "string"}
          - {label: "Message d'Engagement", name: "commitment", widget: "text"}
          - label: "Réseaux Sociaux"
            name: "social"
            widget: "list"
            required: false
            fields:
              - {label: "Plateforme", name: "platform", widget: "select", options: ["Instagram", "LinkedIn", "Facebook", "Twitter"]}
              - {label: "URL", name: "url", widget: "string"}